version: "3.9"

services:
  telegram-bot:
    container_name: telegram
    working_dir: /telegram
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
    command: sh -c "python mixitbot.py"